apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: ingress
spec:
  rules:
  - http:
      paths:
      - path: /question
        backend:
          serviceName: nginx-svc
          servicePort: 80
      - path: /result
        backend:
          serviceName: nginx-svc
          servicePort: 80
      - path: /answer
        backend:
          serviceName: nginx-svc
          servicePort: 80
      - path: /resources
        backend:
          serviceName: nginx-svc
          servicePort: 80
      - path: /
        backend:
          serviceName: rabbitmq-admin
          servicePort: 15672