apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: nginx
  name: nginx
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: nginx
    spec:
      containers:
      - image: nginx:1.19.1-alpine
        name: nginx
        volumeMounts:
        - name: config-volume
          mountPath: /etc/nginx/
        ports:
        - name: http
          containerPort: 80
      volumes:
       - name: config-volume
         configMap:
           name: nginx-conf
