apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: dogorcat
    type: queue
  name: rabbitmq
spec:
  ports:
  - port: 5672
    protocol: TCP
    targetPort: 5672
  selector:
    app: dogorcat
    type: queue
status:
  loadBalancer: {}
