apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: dogorcat
    type: queue
  name: rabbitmq-admin
spec:
  ports:
  - port: 15672
    protocol: TCP
    targetPort: 15672
    nodePort: 30798
  selector:
    app: dogorcat
    type: queue
  type: NodePort
status:
  loadBalancer: {}
