apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: dogorcat
    type: webapp
  name: webapp
spec:
  replicas: 2
  selector:
    matchLabels:
      app: dogorcat
      type: webapp
  template:
    metadata:
      labels:
        app: dogorcat
        type: webapp
    spec:
      containers:
      - image: asia.gcr.io/common-proj-290514/go-webapp:1.2
        name: webapp
        env:
          - name: RABBIT_URL
            value: "rabbitmq:5672"
          - name: RABBIT_USER
            valueFrom:
              secretKeyRef:
                 name: rabbitmq-secret
                 key: RABBITMQ_DEFAULT_USER
          - name: RABBIT_PASSWORD
            valueFrom:
              secretKeyRef:
                 name: rabbitmq-secret
                 key: RABBITMQ_DEFAULT_PASS
          - name: RABBIT_QUEUE_NAME
            value: "dogOrCatQ"
          - name: MYSQL_HOST
            value: "mysql-svc"
          - name: MYSQL_PORT
            value: "3306"
          - name: MYSQL_USER
            valueFrom:
              secretKeyRef:
                 name: mysql-secret
                 key: MYSQL_USER
          - name: MYSQL_PASSWORD
            valueFrom:
              secretKeyRef:
                 name: mysql-secret
                 key: MYSQL_PASSWORD
          - name: MYSQL_DBNAME
            valueFrom:
              secretKeyRef:
                 name: mysql-secret
                 key: MYSQL_DATABASE
          - name: APP_PORT
            value: "80"
        ports:
        - containerPort: 80
          name: app-port

