apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: dogorcat
    type: webapp
  name: webapp-svc
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: dogorcat
    type: webapp
status:
  loadBalancer: {}
